### ISSUE TITLE
klayout master coredumps on rhel6.7 since April 26 Salt commit

### ISSUE THREAD

**Issue by stefanottili** [klayoutmatthias/klayout#14]
last version that compiled and run was April 25 b3e823ca28ce393ed54ec4f3b0e54b8213aea590

rhel6.7, gcc version 4.4.7 20120313 (Red Hat 4.4.7-16) (GCC)

automatically detected: qt-4.8.3, ruby 1.9.3

./build.sh -without-qtbinding -nopython

(gdb) bt
#0  0x00002aaaab0138d6 in tl::XMLElementProxy::XMLElementProxy (this=0x840cf0, d=...) at ../../src/tl/tlXMLParser.cc:198
#1  0x00002aaaab0281cf in __gnu_cxx::new_allocator<tl::XMLElementProxy>::construct (this=0x7fffffffda07, __p=0x840cf0, __val=...)
    at /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ext/new_allocator.h:105
#2  0x00002aaaab027b85 in std::list<tl::XMLElementProxy, std::allocator<tl::XMLElementProxy> >::_M_create_node (this=0x83a4a0, __x=...)
    at /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_list.h:464
#3  0x00002aaaab0271bf in std::list<tl::XMLElementProxy, std::allocator<tl::XMLElementProxy> >::_M_insert (this=0x83a4a0, __position=
    ..., __x=...) at /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_list.h:1407
#4  0x00002aaaab026b5e in std::list<tl::XMLElementProxy, std::allocator<tl::XMLElementProxy> >::push_back (this=0x83a4a0, __x=...)
    at /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_list.h:920
#5  0x00002aaaab0272ee in std::list<tl::XMLElementProxy, std::allocator<tl::XMLElementProxy> >::_M_initialize_dispatch<std::_List_const_iterator<tl::XMLElementProxy> > (this=0x83a4a0, __first=Cannot access memory at address 0x10
)
    at /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_list.h:1361
#6  0x00002aaaab026c05 in std::list<tl::XMLElementProxy, std::allocator<tl::XMLElementProxy> >::list (this=0x83a4a0, __x=
    std::list = {...}) at /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_list.h:533
#7  0x00002aaaab0265c7 in tl::XMLElementList::XMLElementList (this=0x83a4a0) at ../../src/tl/tlXMLParser.h:499
#8  0x00002aaaab02664f in tl::XMLElementBase::XMLElementBase (this=0x7fffffffdc80, name="salt-grain", children=...)
    at ../../src/tl/tlXMLParser.h:628
#9  0x00002aaaae4137ff in tl::XMLElement<lay::SaltGrain, lay::SaltGrains, tl::XMLMemberIterReadAdaptor<lay::SaltGrain const&, std::_List_const_iterator<lay::SaltGrain>, lay::SaltGrains>, tl::XMLMemberAccRefWriteAdaptor<lay::SaltGrain, lay::SaltGrains> >::XMLElement (
    this=0x7fffffffdc80, r=..., w=..., name="salt-grain", children=...) at ../../src/tl/tlXMLParser.h:722
#10 0x00002aaaae413009 in tl::make_element<lay::SaltGrain, lay::SaltGrains::grain_iterator, lay::SaltGrains> (begin=
    (lay::SaltGrains::grain_iterator (lay::SaltGrains::*)(const lay::SaltGrains *)) 0x2aaaae40311a <lay::SaltGrains::begin_grains() const>, end=
    (lay::SaltGrains::grain_iterator (lay::SaltGrains::*)(const lay::SaltGrains *)) 0x2aaaae403138 <lay::SaltGrains::end_grains() const>, setter=
    (void (lay::SaltGrains::*)(lay::SaltGrains *, const lay::SaltGrain &)) 0x2aaaae4116b0 <lay::SaltGrains::add_grain(lay::SaltGrain const&)>, name="salt-grain", children=...) at ../../src/tl/tlXMLParser.h:1716
#11 0x00002aaaae412720 in __static_initialization_and_destruction_0 (__initialize_p=1, __priority=65535)
    at ../../src/lay/laySaltGrains.cc:239
#12 0x00002aaaae412b8e in global constructors keyed to laySaltGrains.cc(void) () at ../../src/lay/laySaltGrains.cc:264
#13 0x00002aaaae45a906 in __do_global_ctors_aux ()
   from klayout-93713d19e1e55a8b1fe030af8aec705d801608c7/bin-debug/libklayout_lay.so.1
#14 0x00002aaaae1689e3 in _init ()
   from klayout-93713d19e1e55a8b1fe030af8aec705d801608c7/bin-debug/libklayout_lay.so.1
#15 0x00002aaab2b4f990 in ?? ()
#16 0x000000302800e625 in _dl_init_internal () from /lib64/ld-linux-x86-64.so.2
#17 0x0000003028000b3a in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
#18 0x0000000000000001 in ?? ()
#19 0x00007fffffffe340 in ?? ()
#20 0x0000000000000000 in ?? ()
(gdb)

**Comment by stefanottili** [comment]
24b213d  fixed the coredump, many thanks
